### ISSUE TITLE
Настроить CI/CD с использованием GitHub Actions, GHCR, и Docker Compose

### ISSUE THREAD

**Issue by qertis** [gotois/ProstoDiary_bot#1269]
#### **Шаг 1: Настройка GitHub Repository**

1. **Добавьте в репозиторий файл `Dockerfile`**:
   - Убедитесь, что в корне проекта есть `Dockerfile` для сборки контейнера.
   - Пример простого `Dockerfile`:
     ```dockerfile
     FROM python:3.9-slim
     WORKDIR /app
     COPY requirements.txt requirements.txt
     RUN pip install -r requirements.txt
     COPY . .
     CMD ["python", "app.py"]
     ```

2. **Добавьте файл `docker-compose.yml`**:
   - Этот файл будет использоваться для запуска проекта на сервере.
   - Пример `docker-compose.yml`:
     ```yaml
     version: '3.8'
     services:
       app:
         image: ghcr.io/<username>/<repo-name>:latest
         ports:
           - "80:80"
         environment:
           - ENV_VAR=value
     ```

3. **Добавьте секреты в GitHub**:
   - Перейдите в **Settings → Secrets and variables → Actions → New repository secret**.
   - Добавьте следующие секреты:
     - `GHCR_PAT`: *Personal Access Token* (с правами на `write:packages` и `read:packages`).
     - `DEPLOY_SERVER`: IP-адрес или доменное имя сервера.
     - `DEPLOY_USER`: SSH-пользователь на сервере.
     - `DEPLOY_KEY`: Приватный ключ SSH (например, из `~/.ssh/id_rsa`).

---

#### **Шаг 2: Настройка GitHub Actions**

1. В репозитории создайте директорию `.github/workflows/`.

2. Добавьте файл `.github/workflows/ci-cd.yml` со следующим содержимым:
   ```yaml
   name: CI/CD Pipeline

   on:
     push:
       branches:
         - master
     pull_request:
       branches:
         - master

   jobs:
     build-and-push:
       name: Build and Push Docker Image
       runs-on: ubuntu-latest

       steps:
         # Шаг 1: Клонирование репозитория
         - name: Checkout repository
           uses: actions/checkout@v3

         # Шаг 2: Логин в GitHub Container Registry
         - name: Log in to GitHub Container Registry
           run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

         # Шаг 3: Сборка и публикация Docker-образа
         - name: Build and Push Docker image
           uses: docker/build-push-action@v5
           with:
             context: .
             tags: |
               ghcr.io/${{ github.repository }}:latest
             push: true

     deploy:
       name: Deploy to Server
       runs-on: ubuntu-latest
       needs: build-and-push

       steps:
         # Шаг 4: Копирование docker-compose.yml на сервер
         - name: Copy docker-compose to server
           uses: appleboy/scp-action@v0.2.1
           with:
             host: ${{ secrets.DEPLOY_SERVER }}
             username: ${{ secrets.DEPLOY_USER }}
             key: ${{ secrets.DEPLOY_KEY }}
             source: docker-compose.yml
             target: ~/project/

         # Шаг 5: Деплой с Docker Compose
         - name: Deploy with Docker Compose
           uses: appleboy/ssh-action@v0.1.7
           with:
             host: ${{ secrets.DEPLOY_SERVER }}
             username: ${{ secrets.DEPLOY_USER }}
             key: ${{ secrets.DEPLOY_KEY }}
             script: |
               cd ~/project
               docker-compose pull
               docker-compose up -d --remove-orphans
   ```

---

#### **Шаг 3: Настройка сервера**

1. **Установите Docker и Docker Compose**:
   - Выполните команды на сервере:
     ```bash
     sudo apt update
     sudo apt install -y docker.io docker-compose
     sudo systemctl enable --now docker
     ```

2. **Настройте SSH-доступ**:
   - Скопируйте свой публичный ключ на сервер:
     ```bash
     ssh-copy-id -i ~/.ssh/id_rsa <DEPLOY_USER>@<DEPLOY_SERVER>
     ```

3. **Создайте директорию для проекта**:
   - Например:
     ```bash
     mkdir -p ~/project
     ```

---

#### **Шаг 4: Проверка CI/CD**

1. **Push изменений в ветку `master`**:
   - Закоммитьте изменения и отправьте их в репозиторий:
     ```bash
     git add .
     git commit -m "Set up CI/CD workflow"
     git push origin main
     ```

2. **Проверьте выполнение workflow**:
   - Перейдите в раздел **Actions** в вашем репозитории на GitHub.
   - Убедитесь, что все шаги pipeline выполнены без ошибок.

3. **Проверьте состояние сервера**:
   - Убедитесь, что контейнеры запущены:
     ```bash
     docker ps
     ```

4. **Проверьте приложение**:
   - Откройте приложение в браузере или выполните:
     ```bash
     curl http://<DEPLOY_SERVER>
     ```

---

#### **Шаг 5: Устранение проблем**

- **Ошибка при логине в GHCR**:
  - Проверьте, что токен `GHCR_PAT` имеет права на `write:packages`.
  - Убедитесь, что вы используете правильный формат образа: `ghcr.io/<username>/<repo-name>:tag`.

- **Ошибка SSH-подключения**:
  - Проверьте, что секрет `DEPLOY_KEY` содержит правильный приватный ключ.
  - Убедитесь, что сервер доступен по указанному IP и порту.

- **Ошибка `docker-compose pull`**:
  - Проверьте, что образ успешно загружен в GHCR.

---

### **Итог**

1. **Репозиторий**: Добавьте `Dockerfile`, `docker-compose.yml`, и настройте секреты.
2. **GitHub Actions**: Настройте workflow для автоматической сборки, пуша и деплоя.
3. **Сервер**: Установите Docker/Compose и настройте SSH.
4. **CI/CD**: Теперь ваш процесс автоматизирован — достаточно пуша в `main` для сборки и развертывания!
